# See https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
# Contains examples on how to set up
project:
  type: website
  output-dir: docs

website:
  title: "Policies for Liberate Science GmbH"
  image: "logo.png"
  favicon: "favicon.png"
  open-graph: true
  site-url: https://libscie.org
  repo-url: https://github.com/libscie/policy
  issue-url: https://github.com/libscie/policy/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  search: 
    location: navbar
    type: overlay
  page-footer:
    left:
      - text: "CC0 Public Domain Dedication"
        href: "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
    right:
      - icon: github
        href: https://github.com/libscie
        aria-label: Liberate Science GmbH GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: LibScie Blog RSS   
      - icon: mastodon
        href: https://akademienl.social/@libscie
        aria-label: LibScie Mastodon
  navbar:
    background: light
    logo: logo.png
    logo-alt: "LibScie logo"
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Getting started"
        menu:
          - href: "onboarding/discord.qmd"
          - href: "onboarding/github.qmd"
          - href: "onboarding/researchequals.qmd"
      - text: "Culture"
        menu: 
          - href: "culture/workweek.qmd"
          - href: "culture/jobs.qmd"
      - text: "Policies"
        menu:
          - href: "policies/coc.qmd"
          - href: "policies/events.qmd"
          - href: "policies/equipment.qmd"
          - href: "policies/wages.qmd"

      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/libscie/policy/issues"
    tools:
      - icon: github
        href: https://github.com/libscie
        text: Liberate Science GmbH GitHub
      - icon: rss
        href: https://libscie.org/rss
        text: LibScie Blog RSS

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    toc: true
    # themes available https://quarto.org/docs/output-formats/html-themes.html
    theme: [cosmo]
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

